let modal = 
{
    openPlus()
    {
        document.querySelector('.modal-overlay').classList.toggle('invisible')
        document.querySelector('.btn-plus').classList.add('z-50')
    },
    /*
    openHand()
    {
        document.querySelector('.modal-overlay').classList.toggle('invisible')
        document.querySelector('.btn-plus').classList.add('z-50')
    },
    open()
    {
        document.querySelector('.modal-overlay').classList.toggle('invisible')
        document.querySelector('.btn-plus').classList.add('z-50')
    },*/
}